<?php

namespace MapBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(){
        $em = $this->getEntityManager();
        $builder = $em->createQueryBuilder();
        $builder
            ->select(array('l'))
            ->from('MapBundle\Entity\Location', 'l');

        $query = $builder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function deleteAll(){
        $em = $this->getEntityManager();
        $builder = $em->createQuery('Delete MapBundle\Entity\Location');
        $results = $builder->getResult();
        return $results;
    }
}
